# Generated by Django 4.2.7 on 2025-11-21 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_producto_marca_producto_modelo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del dispositivo')),
                ('ip', models.GenericIPAddressField(verbose_name='IP del dispositivo')),
                ('marca', models.CharField(blank=True, max_length=50, verbose_name='Marca')),
                ('modelo', models.CharField(blank=True, max_length=100, verbose_name='Modelo')),
                ('protocol', models.CharField(default='SNMP', max_length=20, verbose_name='Protocolo')),
                ('snmp_version', models.CharField(default='2c', max_length=10, verbose_name='SNMP Version')),
                ('snmp_community', models.CharField(blank=True, max_length=100, verbose_name='SNMP Community')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('ultimo_lectura', models.DateTimeField(blank=True, null=True, verbose_name='Última lectura')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='core.producto', verbose_name='Producto consumible')),
            ],
            options={
                'verbose_name': 'Dispositivo',
                'verbose_name_plural': 'Dispositivos',
            },
        ),
    ]
