# Generated by Django 4.2.7 on 2025-12-04 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_barcode'),
        ('core', '0003_device'),
    ]

    operations = [
    ]
