# Generated by Django 4.2.7 on 2025-12-12 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_merge_0003_add_barcode_0003_device'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='ultimo_lectura',
            new_name='ultima_lectura',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='snmp_version',
            new_name='version_snmp',
        ),
        migrations.RemoveField(
            model_name='device',
            name='protocol',
        ),
        migrations.RemoveField(
            model_name='device',
            name='snmp_community',
        ),
        migrations.AddField(
            model_name='device',
            name='comunidad_snmp',
            field=models.CharField(blank=True, max_length=100, verbose_name='SNMP Community'),
        ),
        migrations.AddField(
            model_name='device',
            name='protocolo',
            field=models.CharField(default='SNMP', max_length=20, verbose_name='Protocolo'),
        ),
        migrations.AlterField(
            model_name='device',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos', to='core.producto', verbose_name='Producto consumible'),
        ),
        migrations.AddIndex(
            model_name='alerta',
            index=models.Index(fields=['activa', 'producto'], name='core_alerta_activa_0502d7_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['ip'], name='core_device_ip_d0c141_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['activo', 'producto'], name='core_device_activo_44812f_idx'),
        ),
        migrations.AddIndex(
            model_name='movimiento',
            index=models.Index(fields=['producto', '-fecha'], name='core_movimi_product_004ab4_idx'),
        ),
        migrations.AddIndex(
            model_name='movimiento',
            index=models.Index(fields=['tipo', '-fecha'], name='core_movimi_tipo_1aa512_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['categoria', '-fecha_creacion'], name='core_produc_categor_c8ec76_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['marca', 'modelo'], name='core_produc_marca_1567f6_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['stock'], name='core_produc_stock_2266c3_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['codigo_barras'], name='core_produc_codigo__3bd02c_idx'),
        ),
    ]
