# Generated by Django 4.2.7 on 2025-12-16 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_merge_0003_add_barcode_0003_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='usuario',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Usuario que realizó el movimiento'),
        ),
    ]
